"""Build a macOS application bundle so the tunnel manager opens from a double-click.

macOS has no ``pythonw`` and Finder never executes a plain script, so the bundle ships a
POSIX shell launcher that ``exec``s the checkout interpreter on ``bin/ssh-tunnel-manager.pyw``.

The bundle stays a double-click target of its own by default. It lists ``.pyw`` as an
Alternate-rank document type, which only makes it selectable in Finder's "Open With" menu;
nothing about the current default handler changes until the user opts in — either there, or
once with ``--associate-pyw``.
"""

import argparse
from pathlib import Path
import plistlib
import shutil
import subprocess
import sys
import shlex
import tempfile

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / 'src') not in sys.path:
    sys.path.insert(0, str(ROOT / 'src'))

from platform_support import APP_DISPLAY_NAME, BUNDLE_VERSION  # noqa: E402

APP_NAME = 'SSH Tunnel Manager'
BUNDLE_IDENTIFIER = 'local.ssh-tunnel-manager.app'
EXECUTABLE = 'ssh-tunnel-manager'
PYW_EXTENSION = 'pyw'
# LaunchServices synthesizes this identifier from the extension; no declared type exists for .pyw.
PYW_UNIFORM_TYPE_IDENTIFIER = 'dyn.ah62d4rv4ge81a8p1'
ICON_SIZES = (16, 32, 128, 256, 512)
LSREGISTER = Path('/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks'
                  '/LaunchServices.framework/Versions/A/Support/lsregister')
MISSING_INTERPRETER_HELP = '请先运行 python3 scripts/dev.py 创建虚拟环境，再重新生成启动器。'


def launcher_text(interpreter, entry):
    """POSIX shell that starts the GUI and reports a broken environment natively."""
    quoted = ' '.join((
        'INTERPRETER=' + shlex.quote(str(interpreter)),
        'ENTRY=' + shlex.quote(str(entry)),
    ))
    alert = ('/usr/bin/osascript -e "on run argv" '
             '-e "display alert (item 1 of argv) message (item 2 of argv)" '
             '-e "end run" ' + shlex.quote(APP_DISPLAY_NAME) + ' ' +
             shlex.quote('找不到 Python 解释器：\n' + str(interpreter) + '\n\n' + MISSING_INTERPRETER_HELP))
    return ('#!/bin/sh\n'
            '# Generated by scripts/make_macos_app.py — regenerate instead of editing.\n'
            + quoted + '\n'
            'if [ ! -x "$INTERPRETER" ]; then\n'
            '  ' + alert + ' >/dev/null 2>&1\n'
            '  exit 1\n'
            'fi\n'
            'exec "$INTERPRETER" "$ENTRY" "$@"\n')


def bundle_plist(with_icon):
    """Info.plist contents: application identity plus the selectable ``.pyw`` document type."""
    payload = {
        'CFBundleName': APP_DISPLAY_NAME,
        'CFBundleDisplayName': APP_DISPLAY_NAME,
        'CFBundleExecutable': EXECUTABLE,
        'CFBundleIdentifier': BUNDLE_IDENTIFIER,
        'CFBundleInfoDictionaryVersion': '6.0',
        'CFBundlePackageType': 'APPL',
        'CFBundleShortVersionString': BUNDLE_VERSION,
        'CFBundleVersion': BUNDLE_VERSION,
        # Alternate keeps the bundle out of the default-handler election; Owner would seize every .pyw.
        'CFBundleDocumentTypes': [{
            'CFBundleTypeName': 'Python GUI Script',
            'CFBundleTypeExtensions': [PYW_EXTENSION],
            'CFBundleTypeRole': 'Viewer',
            'LSHandlerRank': 'Alternate',
        }],
        'LSMinimumSystemVersion': '11.0',
        'NSHighResolutionCapable': True,
    }
    if with_icon:
        payload['CFBundleIconFile'] = 'AppIcon'
    return payload


def build_icon(logo, resources):
    """Render the checkout logo into AppIcon.icns; False when the toolchain is unavailable."""
    if not logo.is_file() or not (shutil.which('sips') and shutil.which('iconutil')):
        return False
    with tempfile.TemporaryDirectory(prefix='tunnel-icon-') as folder:
        iconset = Path(folder) / 'AppIcon.iconset'
        iconset.mkdir()
        for size in ICON_SIZES:
            for suffix, pixels in (('', size), ('@2x', size * 2)):
                name = 'icon_{}x{}{}.png'.format(size, size, suffix)
                done = subprocess.run(['sips', '-z', str(pixels), str(pixels), str(logo),
                                       '--out', str(iconset / name)],
                                      stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                if done.returncode:
                    return False
        done = subprocess.run(['iconutil', '-c', 'icns', str(iconset),
                               '-o', str(resources / 'AppIcon.icns')],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return done.returncode == 0


def write_bundle(app, interpreter, entry, logo=None):
    """Create the bundle tree and return the launcher path."""
    contents = app / 'Contents'
    resources = contents / 'Resources'
    macos = contents / 'MacOS'
    macos.mkdir(parents=True, exist_ok=True)
    resources.mkdir(parents=True, exist_ok=True)
    launcher = macos / EXECUTABLE
    launcher.write_text(launcher_text(interpreter, entry), encoding='utf-8')
    launcher.chmod(0o755)
    has_icon = build_icon(logo, resources) if logo is not None else False
    with (contents / 'Info.plist').open('wb') as stream:
        plistlib.dump(bundle_plist(has_icon), stream)
    (contents / 'PkgInfo').write_bytes(b'APPL????')
    return launcher


def register(app):
    if LSREGISTER.is_file():
        subprocess.run([str(LSREGISTER), '-f', str(app)], check=False)


def sign(app):
    """Ad-hoc signature keeps LaunchServices and Gatekeeper happy for a locally built bundle."""
    if not shutil.which('codesign'):
        return False
    return subprocess.run(['codesign', '--force', '--sign', '-', str(app)],
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0


def associate_pyw():
    """Opt-in only: make the bundle the default handler for .pyw, leaving the .py editor alone."""
    try:
        import LaunchServices as services
    except ImportError:
        return False
    status = services.LSSetDefaultRoleHandlerForContentType(PYW_UNIFORM_TYPE_IDENTIFIER,
                                                            services.kLSRolesAll, BUNDLE_IDENTIFIER)
    return status == 0


def parse_arguments(argv):
    parser = argparse.ArgumentParser(description='生成 macOS 启动器 app bundle')
    parser.add_argument('--output', default=str(Path.home() / 'Applications'),
                        help='app bundle 的父目录，默认 ~/Applications')
    parser.add_argument('--interpreter', default=sys.executable, help='启动界面使用的 Python 解释器')
    parser.add_argument('--force', action='store_true', help='覆盖已存在的 app bundle')
    parser.add_argument('--no-icon', action='store_true', help='跳过 AppIcon.icns 生成')
    parser.add_argument('--associate-pyw', action='store_true',
                        help='额外把 .pyw 的默认打开程序设为该 bundle（机器级改动，默认不做）')
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_arguments(argv)
    if sys.platform != 'darwin':
        print('仅 macOS 需要 app bundle；Windows/Linux 请直接使用 bin 下的入口。')
        return 1

    entry = ROOT / 'bin' / 'ssh-tunnel-manager.pyw'
    interpreter = Path(args.interpreter)
    if not interpreter.is_file():
        print('警告：解释器不存在（{}），启动器运行时会提示安装步骤。'.format(interpreter))

    output = Path(args.output).expanduser()
    app = output / (APP_NAME + '.app')
    if app.exists():
        if not args.force:
            print('已存在 {}，请加 --force 覆盖。'.format(app))
            return 1
        shutil.rmtree(app)
    output.mkdir(parents=True, exist_ok=True)

    write_bundle(app, interpreter, entry, logo=None if args.no_icon else ROOT / 'src' / 'assets' / 'app_logo.png')
    register(app)
    signed = sign(app)
    print('已生成 {}'.format(app))
    if not signed:
        print('提示：未完成代码签名，首次双击若被 Gatekeeper 拦截请右键选择“打开”。')
    print('双击 {} 打开界面；在 Dock 上右键图标 →“选项 → 在 Dock 中保留”即可常驻。'.format(app.name))
    if args.associate_pyw:
        if associate_pyw():
            print('已将 .{} 的默认打开程序指向该 bundle：双击任意 .{} 文件都会启动本程序。'
                  .format(PYW_EXTENSION, PYW_EXTENSION))
        else:
            print('默认程序设置失败（LaunchServices 不可用），请在 Finder 的“显示简介 → 打开方式”里手工选择。')
    else:
        print('双击 ssh_tunnel_manager.{}：右键该文件 →“打开方式 → {}”即可单次启动，不改动系统默认程序。'
              .format(PYW_EXTENSION, APP_NAME))
    print('移动程序或重建虚拟环境后请重新运行本脚本（启动器记录的是绝对路径）。')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
